#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

FILES=$(git diff --name-only --cached --diff-filter=ACM -- "*.[ch]")
if [[ -z "${FILES}" ]]; then
    exit 0
fi

# shellcheck disable=SC2086
if ! clang-format \
        --dry-run \
        --Werror \
        --ferror-limit=1 \
        ${FILES} \
        &> /dev/null; then
    printf "** ERROR: Staged code is not formatted correctly.\n"
    exit 1
fi

exit 0
