#
# Github workflow 
#

name: CI-Build 
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 6"
jobs:
  docker-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
        xdg_session_type: [x11, wayland]
        docker_image: [archlinux-build, fedora-build, ubuntu-build]
    env:
      ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
      XDG_SESSION_TYPE: ${{ matrix.xdg_session_type }}
      CMD: |
        make \
          GITHUB_REF=${GITHUB_REF} \
          GITHUB_RUN_ID=${GITHUB_RUN_ID} \
          GITHUB_SHA=${GITHUB_SHA} \
          GITHUB_JOB=${GITHUB_JOB} \
          CC=${{ matrix.compiler }} \
          EXTRA_CFLAGS=-Werror \
          artifactory-upload
    if: true 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create and run docker image
        run: make -f docker/Makefile ${{ matrix.docker_image }}

